version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "yaorlov"
    default_labels:
      - "dependencies"
      - "dependabot"
    allowed_updates:
      - match:
          update_type: "security"
